- name: Deploy app
  hosts: localhost
  gather_facts: true
  become: false
  environment:
    K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'HOME') + '/.kube/config' }}"

  tasks:
    - name: Slurp app3.html
      ansible.builtin.slurp:
        src: "index.html"
      register: app3

    - name: Create the configmap for app3.html from slurp
      kubernetes.core.k8s:
        state: present
        namespace: default
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: cm-app3
          data:
            index.html: "{{ app3.content | b64decode }}"

    - name: Create a ClusterIP for nginx app
      kubernetes.core.k8s:
        state: present
        src: service.yaml

    - name: Create a Deployment for nginx app
      kubernetes.core.k8s:
        state: present
        src: deployment.yaml
