- name: Add hosts of inventory file to known hosts
  hosts: localhost
  gather_facts: false

  vars:
    known_host_file: "{{ lookup('env', 'HOME') + '/.ssh/known_hosts' }}"
    hosts_to_add: "{{ groups['all'] }}"

  tasks:
    - name: Scan ssh public key of hosts
      ansible.builtin.shell: "ssh-keyscan {{item}} `dig {{item}} +short`"
      register: ssh_scan_keys
      with_items: "{{ hosts_to_add }}"
      ignore_errors : true

    - name: Remove public key of previous create hosts to know_hosts file
      ansible.builtin.known_hosts:
        name: "{{ item.item }}"
        path: "{{known_host_file}}"
        state: absent
      with_items: "{{ ssh_scan_keys.results }}"
      when: ssh_scan_keys.results | length > 0

    - name: Add public key of hosts to know_hosts file
      ansible.builtin.known_hosts:
        name: "{{ item.item }}"
        key: "{{item.stdout}}"
        path: "{{known_host_file}}"
        state: present
      with_items: "{{ ssh_scan_keys.results }}"
      when: ssh_scan_keys.results | length > 0

    - name: Debug
      ansible.builtin.debug:
        msg:
        - "known_host_file: {{ known_host_file }}"
        - "hosts_to_add: {{ hosts_to_add }}"
        - "ssh_scan_keys: {{ ssh_scan_keys }}"
      tags: [ 'never', 'debug' ]
