- name: Setup master node
  hosts: master
  gather_facts: true
  become: true
  vars:

  tasks:
    - name: Gather services facts
      ansible.builtin.service_facts:

    - name: Install k3s
      ansible.builtin.debug:
        msg: "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC=\"--tls-san {{master_node_ip}} --node-external-ip {{master_node_ip}}\" K3S_KUBECONFIG_MODE=644 sh -"
      become: false
      when: services['k3s.service'] is not defined

    - name: Install k3s
      ansible.builtin.shell:
        cmd: "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC=\"--tls-san {{master_node_ip}} --node-external-ip {{master_node_ip}}\" K3S_KUBECONFIG_MODE=644 sh -"
      become: false
      when: services['k3s.service'] is not defined

    - name: Gather services facts
      ansible.builtin.service_facts:

    - name: Wait for token to be generated
      ansible.builtin.wait_for:
        path: /var/lib/rancher/k3s/server/node-token
      when: services['k3s.service'] is defined

    - name: Fetch token on host
      ansible.builtin.fetch:
        src: /var/lib/rancher/k3s/server/node-token
        dest: /tmp/node-token
        flat: true
