apiVersion: v1
kind: Service
metadata:
  name: argo-service
  namespace: argo-cd
spec:
  type: NodePort
  ports:
    - port: 443
      nodePort: 30001
  selector:
    app.kubernetes.io/name: argocd-server
