- name: Deploy app
  hosts: localhost
  gather_facts: true
  become: false
  environment:
    K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'HOME') + '/.kube/config' }}"

  tasks:
    - name: Update and deploy custom ArgoCD Chart
      kubernetes.core.helm:
        name: argo-cd
        dependency_update: true #run helm dep update CHART before operation
        chart_ref: charts/argo-cd
        release_namespace: argo-cd
        create_namespace: true
        values_files:
          - charts/argo-cd/values.yaml

    - name: Patch ArgoCD ClusterIP into a NodePort
      kubernetes.core.k8s:
        namespace: argo-cd
        state: patched
        kind: Service
        name: argo-cd-argocd-server
        definition:
          spec:
            type: NodePort
            ports:
              - port: 80
                nodePort: 30001

    - name: Retrieve Secret with admin pass
      kubernetes.core.k8s_info:
        kind: Secret
        namespace: argo-cd
        name: argocd-initial-admin-secret
        wait: yes
        wait_sleep: 2
        wait_timeout: 600
      register: argo_admin_pass

    - name: Print admin pass
      ansible.builtin.debug:
        msg: "{{ argo_admin_pass.resources[0].data.password | b64decode}}"

    - name: Save admin pass to file
      ansible.builtin.copy:
        content: "{{ argo_admin_pass.resources[0].data.password | b64decode}}"
        dest: "{{ lookup('env', 'PWD') }}/admin_pass.txt"

    # TODO: Separate me in a different file for the root-app
    - name: Create dev namespace
      kubernetes.core.k8s:
        name: dev
        api_version: v1
        kind: Namespace
        state: present

    - name: Slurp SSH key into register
      ansible.builtin.slurp:
        src: "{{ lookup('env', 'PWD') }}/ssh/id_ed"
      register: ssh_private_key

    - name: Create a secret for argoCD with ssh key
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: private-repo
            namespace: argo-cd
            labels:
              argocd.argoproj.io/secret-type: repo-creds
          stringData:
            type: git
            url: git@github.com:fleblay
            sshPrivateKey: |
              -----BEGIN OPENSSH PRIVATE KEY-----
              {{ ssh_private_key.content | b64decode | trim }}
              -----END OPENSSH PRIVATE KEY-----

    #TODO: CREATE ROOT APP
    - name: Deploy root-app Chart
      kubernetes.core.helm:
        name: root-app
        chart_ref: charts/root-app
        release_namespace: argo-cd
