#ansible-galaxy collection install ansible.posix -> for ssh
- name: Setup of nodes
  hosts: all
  gather_facts: true
  become: true
  vars:

  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Install curl
      ansible.builtin.apt:
        name: curl
        state: latest

    - name: Install htop
      ansible.builtin.apt:
        name: htop
        state: latest

    # - name: K8s ansible remote dependency - Install python3
    #   ansible.builtin.apt:
    #     name: python3
    #     state: latest
    #
    # - name: K8s ansible remote dependency - Install python3-yaml
    #   ansible.builtin.apt:
    #     name: python3-yaml
    #     state: latest
    #
    # - name: K8s ansible remote dependency - Install python3-kubernetes
    #   ansible.builtin.apt:
    #     name: python3-kubernetes
    #     state: latest
