apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: default
  labels:
    app: nginx-app
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      name: nginx
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: vol-app-1
              mountPath: "/usr/share/nginx/html"
              readOnly: true
      volumes:
        - name: vol-app-1
          configMap:
            name: cm-app-1
