apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  namespace: default
  labels:
    app: nginx-app
spec:
  selector:
    matchLabels:
      app: app2
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: app2
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: vol-app2
              mountPath: "/usr/share/nginx/html"
              readOnly: true
      volumes:
        - name: vol-app2
          configMap:
            name: cm-app2
