spec:
  template:
    spec:
      hostAliases: #For registration of the runner
        - ip: "192.168.42.111"
          hostnames:
            - "gitlab.example.com"
      containers:
        - name: gitlab-gitlab-runner
          # env:
          #   - name: CI_SERVER_URL
          #     value: http://gitlab.example.com
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - /configmaps/check-live
                # - /bin/ls
          readinessProbe:
            exec:
              command:
                - /usr/bin/pgrep
                - gitlab.*runner
                # - /bin/ls
          securityContext: #login as root in container for debug purposes
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0
            runAsNonRoot: false
