#available keys : https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/values.yaml?ref_type=heads
gitlab:
  global:
    ingress:
      enabled: false
      configureCertmanager: false
  nginx-ingress:
    enabled: false
  certmanager:
    install: false
  gitlab:
    webservice:
      minReplicas: 1
      maxReplicas: 1
    gitlab-shell:
      minReplicas: 1
      maxReplicas: 1
    kas:
      minReplicas: 1
      maxReplicas: 1
    sidekiq:
      minReplicas: 1
      maxReplicas: 1
  registry:
    hpa:
      minReplicas: 1
      maxReplicas: 1
