variables:
  GIT_SSL_NO_VERIFY: true
  TAG: $(date +%Y-%m-%d-%H%M)
  APP_NAME: fleblay-42
  DOCKER_NAMESPACE: fleblay
  IMAGE_NAME: "${DOCKER_NAMESPACE}/${APP_NAME}"
  IMAGE_NAME_WITH_TAG: "${IMAGE_NAME}:${TAG}"
  CI_CD_DOCKER_USER: fleblay
  #TODO: Create CI_CD_DOCKER_PASSWORD in gitlab env variables
  #TODO Genreate github access token via https://github.com/settings/tokens/new with repo rights and create CI_GITHUB_TOKEN in gitlab env variables

default:
  before_script:
    - apt-get update
    - apt-get install -y git yq

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo "This job tests something"

build:
  stage: build
  image: debian:bookworm-slim
  before_script:
    - apt-get update
    - apt-get install -y git
  script:
    - echo $CI_CD_DOCKER_PASSWORD | docker login -u $CI_CD_DOCKER_USER --password-stdin
    - docker build -t $APP_NAME:$TAG .
    - docker push $IMAGE_NAME_WITH_TAG
  rules:
    - if: $CI_COMMIT_REF_NAME != main
      when: never

deploy:
  stage: deploy
  image: debian:bookworm-slim
  before_script:
    - apt-get update
    - apt-get install -y yq
  script:
    - git clone https://$CI_GITHUB_TOKEN@github.com/fleblay/42app.git
    - cd 42app
    - yq -i '(.spec.template.spec.containers[] | select(.name == "42app") | .image) = strenv(IMAGE_NAME_WITH_TAG)"' app/deployment.yaml
    - git add app/deployment
    - git commit -m "CI deploy $TAG"
    - git push -o ci.skip
  rules:
    - if: $CI_COMMIT_REF_NAME != main
      when: never
